# Default values for appofapps

# clusters is a dictionary listing the target clusters
# clusters:
#   cluster1: 'https://cluster1-addr1:por1'
#   cluster2: 'https://cluster2-addr2:por2'
clusters: {}

# the applications will automatically sync
autosync: true

# the clusters will be rolled out one after the other
sequential: true

remoteChart:
  name: "prometheus"
  repo: "https://kubernetes-charts.storage.googleapis.com"
  revision: "11.12.0"
  values: {}

