---
name: CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      HELM_VERSION: "v3.3.4"

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Helm Install
      run: |
        curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -o helm-${HELM_VERSION}-linux-amd64.tar.gz \
        && curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz.sha256sum -o helm-${HELM_VERSION}-linux-amd64.tar.gz.sha256sum \
        sha256sum -c helm-${HELM_VERSION}-linux-amd64.tar.gz.sha256sum \
        && sudo mv -v linux-amd64/helm /usr/local/bin/helm \
        && rm -vrf linux-amd64
    - name: SHA check
    - name: Lint
      run: helm lint .
    - name: Should template test1
      run: |
        helm template . --values tests/appofapps_test1.yaml

