---
name: CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      HELM_VERSION: "v3.3.2"

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Helm Install
      run: |
        curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz \
          | tar vxz \
            && sudo mv -v linux-amd64/helm /usr/local/bin/helm \
            && rm -vrf linux-amd64
    - name: Lint
      run: helm lint .
    - name: Should template test1
      run: |
        helm template . --values tests/appofapps_test1.yaml

