---
name: CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      HELM_VERSION: "v3.3.4"
      HELM_CHECKSUM: "b664632683c36446deeb85c406871590d879491e3de18978b426769e43a1e82c"
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Helm Install
      run: |
        curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -o helm-${HELM_VERSION}-linux-amd64.tar.gz \
        && curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz.sha256sum -o helm-${HELM_VERSION}-linux-amd64.tar.gz.sha256sum \
        && echo "${HELM_CHECKSUM} helm-${HELM_VERSION}-linux-amd64.tar.gz" | sha256sum -c \
        && tar zxvf helm-${HELM_VERSION}-linux-amd64.tar.gz \
        && sudo mv -v linux-amd64/helm /usr/local/bin/helm \
        && rm -vrf linux-amd64
    - name: Lint
      run: helm lint .
    - name: Should template test1
      run: |
        helm template . --values tests/appofapps_test1.yaml

